import java.util.HashMap;

/**
 * Class that holds the information of cities, taken from the Rest-Countries API.
 * We modified the string that returned from a query for all countries to make an ArrayList, because waiting
 * for the API to return a result took a lot of time and there's not that many countries anyway, so we could
 * save them in memory.
 */
public class Cities {

    /**
     * Creates a HashMap with all the info needed from Rest-Countries.
     * @return HashMap with keys being the city and the value being a String[] A
     * such that A[0]=country, A[1]=currency and A[2]=population
     */
    public static HashMap<String, String[]> get_cities_dictionary() {
        
        String[] list = {"STOCKHOLM","SWEDEN", "SEK", "9.89M","GEORGETOWN","GUYANA", "GYD", "746.9K","WILLEMSTAD",
        "CURASAO", "ANG", "154.84K","KUWAIT CITY","KUWAIT", "KWD", "4.18M","KINGSTON",
        "NORFOLK ISLAND", "AUD", "2.30K","RIYADH","SAUDI ARABIA", "SAR", "32.24M","BAKU",
        "AZERBAIJAN", "AZN", "9.73M","SANTIAGO","CHILE", "CLP", "18.19M","GEORGE TOWN",
        "CAYMAN ISLANDS", "KYD", "58.23K","BRATISLAVA","SLOVAKIA", "EUR", "5.42M","BERLIN",
        "GERMANY", "EUR", "81.77M","JUBA","SOUTH SUDAN", "SSP", "12.13M","LISBON","PORTUGAL", "EUR", "10.37M",
        "KATHMANDU","NEPAL", "NPR", "28.43M","JAMESTOWN",
        "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "SHP", "4.25K","PANAMA CITY","PANAMA", "PAB", "3.81M",
        "SAINT HELIER","JERSEY", "GBP", "100.8K","MARIEHAMN","ALAND ISLANDS", "EUR", "28.87K","NEW DELHI",
        "INDIA", "INR", "1.29B","PORT VILA","VANUATU", "VUV", "277.5K","SOUTH TARAWA","KIRIBATI", "AUD", "113.4K",
        "DOHA","QATAR", "QAR", "2.58M","HARARE","ZIMBABWE", "BWP", "14.24M","NAIROBI","KENYA", "KES", "47.25M",
        "PORTO-NOVO","BENIN", "XOF", "10.65M","PRAIA","CABO VERDE", "CVE", "531.23K","DAMASCUS",
        "SYRIAN ARAB REPUBLIC", "SYP", "18.56M","FLYING FISH COVE","CHRISTMAS ISLAND", "AUD", "2.07K","SAINT-DENIS",
        "REUNION", "EUR", "840.97K","LUANDA","ANGOLA", "AOA", "25.86M","ALOFI","NIUE", "NZD", "1.47K",
        "CHARLOTTE AMALIE","VIRGIN ISLANDS (U.S.)", "USD", "114.74K","GUATEMALA CITY","GUATEMALA", "GTQ", "16.17M",
        "OUAGADOUGOU","BURKINA FASO", "XOF", "19.03M","RABAT","MOROCCO", "MAD", "33.33M","KINGSTOWN",
        "SAINT VINCENT AND THE GRENADINES", "XCD", "109.99K","NIAMEY","NIGER", "XOF", "20.71M","HAMILTON",
        "BERMUDA", "BMD", "61.95K","GIBRALTAR","GIBRALTAR", "GIP", "33.14K","DAKAR","SENEGAL", "XOF", "14.79M",
        "MOGADISHU","SOMALIA", "SOS", "11.07M","WARSAW","POLAND", "PLN", "38.43M","DUSHANBE",
        "TAJIKISTAN", "TJS", "8.59M","SAO TOME","SAO TOME AND PRINCIPE", "STD", "187.35K","YAREN",
        "NAURU", "AUD", "10.08K","CAIRO","EGYPT", "EGP", "91.29M","SOFIA","BULGARIA", "BGN", "7.15M",
        "SAN SALVADOR","EL SALVADOR", "USD", "6.52M","ADAMSTOWN","PITCAIRN", "NZD", "56","PORT LOUIS",
        "MAURITIUS", "MUR", "1.26M","MAMOUDZOU","MAYOTTE", "EUR", "226.91K","MONTEVIDEO","URUGUAY", "UYU", "3.48M",
        "MATA-UTU","WALLIS AND FUTUNA", "XPF", "11.75K","JERUSALEM","ISRAEL", "ILS", "8.52M","KAMPALA",
        "UGANDA", "UGX", "33.86M","APIA","SAMOA", "WST", "194.89K","MEXICO CITY","MEXICO", "MXN", "122.27M",
        "BELGRADE","SERBIA", "RSD", "7.07M","JAKARTA","INDONESIA", "IDR", "258.70M","MOSCOW",
        "RUSSIAN FEDERATION", "RUB", "146.59M","HANOI","VIET NAM", "VND", "92.7M","VIENTIANE",
        "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LAK", "6.49M","DOUGLAS","ISLE OF MAN", "GBP", "84.49K","HONIARA",
        "SOLOMON ISLANDS", "SBD", "642","MALABO","EQUATORIAL GUINEA", "XAF", "1.22M","LJUBLJANA",
        "SLOVENIA", "EUR", "2.06M","TALLINN","ESTONIA", "EUR", "1.31M","ASUNCION","PARAGUAY", "PYG", "6.85M",
        "DIEGO GARCIA","BRITISH INDIAN OCEAN TERRITORY", "USD", "3","YAOUNDE","CAMEROON", "XAF", "22.70M",
        "BRUSSELS","BELGIUM", "EUR", "11.31M","ASTANA","KAZAKHSTAN", "KZT", "17.75M","TBILISI",
        "GEORGIA", "GEL", "3.72M","LUSAKA","ZAMBIA", "ZMW", "15.93M","BUDAPEST","HUNGARY", "HUF", "9.82M",
        "SAINT-PIERRE","SAINT PIERRE AND MIQUELON", "EUR", "6.06K","BERN","SWITZERLAND", "CHF", "8.34M",
        "SINGAPORE","SINGAPORE", "BND", "5.53M","CHISINAU","MOLDOVA (REPUBLIC OF)", "MDL", "3.55M","ULAN BATOR",
        "MONGOLIA", "MNT", "3.09M","AMMAN","JORDAN", "JOD", "9.53M","PORT-AUX-FRANCAIS",
        "FRENCH SOUTHERN TERRITORIES", "EUR", "140","PLYMOUTH","MONTSERRAT", "XCD", "4.92K","VILNIUS",
        "LITHUANIA", "EUR", "2.87M","AMSTERDAM","NETHERLANDS", "EUR", "17.01M","BISHKEK",
        "KYRGYZSTAN", "KGS", "6.04M","WEST ISLAND","COCOS (KEELING) ISLANDS", "AUD", "550","EL AAIUN",
        "WESTERN SAHARA", "MAD", "510.71K","NOUMEA","NEW CALEDONIA", "XPF", "268.76K","PARIS",
        "FRANCE", "EUR", "66.71M","CAYENNE","FRENCH GUIANA", "EUR", "254.54K","KABUL",
        "AFGHANISTAN", "AFN", "27.65M","FUNAFUTI","TUVALU", "AUD", "10.64K","WINDHOEK","NAMIBIA", "NAD", "2.32M",
        "BASSETERRE","SAINT KITTS AND NEVIS", "XCD", "46.20K","TASHKENT","UZBEKISTAN", "UZS", "31.57M",
        "BANDAR SERI BEGAWAN","BRUNEI DARUSSALAM", "BND", "411.9K","NASSAU","BAHAMAS", "BSD", "378.04K",
        "NUKU'ALOFA","TONGA", "TOP", "103.25K","KUALA LUMPUR","MALAYSIA", "MYR", "31.40M","YAMOUSSOUKRO",
        "COTE D'IVOIRE", "XOF", "22.67M","ROAD TOWN","VIRGIN ISLANDS (BRITISH)", "", "28.51K","BUCHAREST",
        "ROMANIA", "RON", "19.86M","MARIGOT","SAINT MARTIN (FRENCH PART)", "EUR", "36.97K","NAYPYIDAW",
        "MYANMAR", "MMK", "51.41M","KIEV","UKRAINE", "UAH", "42.69M","BELMOPAN","BELIZE", "BZD", "370.3K",
        "KIGALI","RWANDA", "RWF", "11.55M","DUBLIN","IRELAND", "EUR", "6.37M","SKOPJE",
        "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)", "MKD", "2.05M","OTTAWA","CANADA", "CAD", "36.15M",
        "SAINT JOHN'S","ANTIGUA AND BARBUDA", "XCD", "86.29K","MONACO","MONACO", "EUR", "38.4K","BAMAKO",
        "MALI", "XOF", "18.13M","PRISTINA","REPUBLIC OF KOSOVO", "EUR", "1.73M","BISSAU",
        "GUINEA-BISSAU", "XOF", "1.54M","TAIPEI","TAIWAN", "TWD", "23.50M","AVARUA","COOK ISLANDS", "NZD", "18.1K",
        "ALGIERS","ALGERIA", "DZD", "40.4M","ADDIS ABABA","ETHIOPIA", "ETB", "92.20M","DILI",
        "TIMOR-LESTE", "USD", "1.16M","VALLETTA","MALTA", "EUR", "425.38K","CANBERRA","AUSTRALIA", "AUD", "24.11M",
        "N'DJAMENA","CHAD", "XAF", "14.49M","MADRID","SPAIN", "EUR", "46.43M","PRAGUE",
        "CZECH REPUBLIC", "CZK", "10.55M","CITY OF VICTORIA","HONG KONG", "HKD", "7.32M","KHARTOUM",
        "SUDAN", "SDG", "39.59M","SUCRE","BOLIVIA (PLURINATIONAL STATE OF)", "BOB", "10.98M","WASHINGTON, D.C.",
        "UNITED STATES OF AMERICA", "USD", "323.94M","TEHRAN","IRAN (ISLAMIC REPUBLIC OF)", "IRR", "79.36M",
        "PORT-AU-PRINCE","HAITI", "HTG", "11.07M","TEGUCIGALPA","HONDURAS", "HNL", "8.57M","LIMA",
        "PERU", "PEN", "31.48M","QUITO","ECUADOR", "USD", "16.54M","ABU DHABI",
        "UNITED ARAB EMIRATES", "AED", "9.85M","SANA'A","YEMEN", "YER", "27.47M","DODOMA",
        "TANZANIA, UNITED REPUBLIC OF", "TZS", "55.15M","THE VALLEY","ANGUILLA", "XCD", "13.45K","ROME",
        "ITALY", "EUR", "60.66M","LIBREVILLE","GABON", "XAF", "1.80M","NUUK","GREENLAND", "DKK", "55.84K",
        "PAPEETE","FRENCH POLYNESIA", "XPF", "271.8K","COLOMBO","SRI LANKA", "LKR", "20.96M","PRETORIA",
        "SOUTH AFRICA", "ZAR", "55.65M","MUSCAT","OMAN", "OMR", "4.42M","KING EDWARD POINT",
        "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "GBP", "30","CARACAS",
        "VENEZUELA (BOLIVARIAN REPUBLIC OF)", "VEF", "31.02M","BANJUL","GAMBIA", "GMD", "1.88M","ISLAMABAD",
        "PAKISTAN", "PKR", "194.12M","BRAZZAVILLE","CONGO", "XAF", "4.74M","PORT OF SPAIN",
        "TRINIDAD AND TOBAGO", "TTD", "1.34M","NOUAKCHOTT","MAURITANIA", "MRO", "3.71M","ST. PETER PORT",
        "GUERNSEY", "GBP", "62.99K","LOME","TOGO", "XOF", "7.14M","PHILIPSBURG",
        "SINT MAARTEN (DUTCH PART)", "ANG", "38.24K","BRIDGETOWN","BARBADOS", "BBD", "285","BEIJING",
        "CHINA", "CNY", "1.37B","LONGYEARBYEN","SVALBARD AND JAN MAYEN", "NOK", "2.56K","COCKBURN TOWN",
        "TURKS AND CAICOS ISLANDS", "USD", "31.45K","ST. GEORGE'S","GRENADA", "XCD", "103.32K","MAJURO",
        "MARSHALL ISLANDS", "USD", "54.88K","RIGA","LATVIA", "EUR", "1.96M","WELLINGTON",
        "NEW ZEALAND", "NZD", "4.69M","PHNOM PENH","CAMBODIA", "KHR", "15.62M","BUJUMBURA",
        "BURUNDI", "BIF", "10.11M","MANAMA","BAHRAIN", "BHD", "1.40M","TIRANA","ALBANIA", "ALL", "2.88M","SEOUL",
        "KOREA (REPUBLIC OF)", "KRW", "50.80M","CASTRIES","SAINT LUCIA", "XCD", "186","HAGATNA",
        "GUAM", "USD", "184.2K","FORT-DE-FRANCE","MARTINIQUE", "EUR", "378.24K","MANAGUA",
        "NICARAGUA", "NIO", "6.26M","TORSHAVN","FAROE ISLANDS", "DKK", "49.37K","DHAKA",
        "BANGLADESH", "BDT", "161.00M","ROSEAU","DOMINICA", "XCD", "71.29K","PAGO PAGO",
        "AMERICAN SAMOA", "USD", "57.1K","ASHGABAT","TURKMENISTAN", "TMT", "4.75M","GUSTAVIA",
        "SAINT BARTHELEMY", "EUR", "9.41K","ZAGREB","CROATIA", "HRK", "4.19M","VADUZ",
        "LIECHTENSTEIN", "CHF", "37.62K","BANGUI","CENTRAL AFRICAN REPUBLIC", "XAF", "4.99M","REYKJAVIK",
        "ICELAND", "ISK", "334.3K","BUENOS AIRES","ARGENTINA", "ARS", "43.59M","TRIPOLI","LIBYA", "LYD", "6.38M",
        "PODGORICA","MONTENEGRO", "EUR", "621.81K","MINSK","BELARUS", "BYN", "9.49M","LONDON",
        "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND", "GBP", "65.11M","MAPUTO",
        "MOZAMBIQUE", "MZN", "26.42M","ASMARA","ERITREA", "ERN", "5.35M","MORONI","COMOROS", "KMF", "806.15K",
        "LILONGWE","MALAWI", "MWK", "16.83M","ABUJA","NIGERIA", "NGN", "186.98M","NICOSIA",
        "CYPRUS", "EUR", "847","SAN JUAN","PUERTO RICO", "USD", "3.47M","PORT MORESBY",
        "PAPUA NEW GUINEA", "PGK", "8.08M","HELSINKI","FINLAND", "EUR", "5.49M","TOKYO","JAPAN", "JPY", "126.96M",
        "ATHENS","GREECE", "EUR", "10.85M","LUXEMBOURG","LUXEMBOURG", "EUR", "576.2K","GABORONE",
        "BOTSWANA", "BWP", "2.14M","BANGKOK","THAILAND", "THB", "65.32M","MONROVIA","LIBERIA", "LRD", "4.61M",
        "MASERU","LESOTHO", "LSL", "1.89M","CONAKRY","GUINEA", "GNF", "12.94M","SARAJEVO",
        "BOSNIA AND HERZEGOVINA", "BAM", "3.53M","MANILA","PHILIPPINES", "PHP", "103.27M","STANLEY",
        "FALKLAND ISLANDS (MALVINAS)", "FKP", "2.56K","PALIKIR","MICRONESIA (FEDERATED STATES OF)", "", "102.8K",
        "SAIPAN","NORTHERN MARIANA ISLANDS", "USD", "56.94K","ORANJESTAD","ARUBA", "AWG", "107.39K","BOGOTA",
        "COLOMBIA", "COP", "48.75M","BRASILIA","BRAZIL", "BRL", "206.13M","PARAMARIBO",
        "SURINAME", "SRD", "541.63K","NGERULMUD","PALAU", "(NONE)", "17.95K","SAN JOSE",
        "COSTA RICA", "CRC", "4.89M","DJIBOUTI","DJIBOUTI", "DJF", "900","ACCRA","GHANA", "GHS", "27.67M",
        "COPENHAGEN","DENMARK", "DKK", "5.71M","VICTORIA","SEYCHELLES", "SCR", "91.4K","THIMPHU",
        "BHUTAN", "BTN", "775.62K","YEREVAN","ARMENIA", "AMD", "2.99M","KINSHASA",
        "CONGO (DEMOCRATIC REPUBLIC OF THE)", "CDF", "85.02M","ANKARA","TURKEY", "TRY", "78.74M","HAVANA",
        "CUBA", "CUC", "11.23M","FAKAOFO","TOKELAU", "NZD", "1.41K","KRALENDIJK",
        "BONAIRE, SINT EUSTATIUS AND SABA", "USD", "17.40K","OSLO","NORWAY", "NOK", "5.22M","FREETOWN",
        "SIERRA LEONE", "SLL", "7.07M","ANDORRA LA VELLA","ANDORRA", "EUR", "78.01K","ANTANANARIVO",
        "MADAGASCAR", "MGA", "22.43M","SANTO DOMINGO","DOMINICAN REPUBLIC", "DOP", "10.07M","BASSE-TERRE",
        "GUADELOUPE", "EUR", "400.13K","LOBAMBA","SWAZILAND", "SZL", "1.13M","BAGHDAD","IRAQ", "IQD", "37.88M",
        "SUVA","FIJI", "FJD", "867","CITY OF SAN MARINO","SAN MARINO", "EUR", "33.00K","PYONGYANG",
        "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)", "KPW", "25.28M","TUNIS","TUNISIA", "TND", "11.15M","MALE",
        "MALDIVES", "MVR", "344.02K","BEIRUT","LEBANON", "LBP", "5.98M","RAMALLAH",
        "PALESTINE, STATE OF", "ILS", "4.68M","VIENNA","AUSTRIA", "EUR", "8.72M",};

        HashMap<String, String[]> map = new HashMap<>();
        String city = "";
        String[] data = new String[3];
        for (int i=0; i < list.length; i++) {
            String string = list[i];
            switch (i%4){
                case 0: city = string; break;
                case 1: data[0] = string; break;
                case 2: data[1] = string; break;
                case 3: {
                    data[2] = string;
                    map.put(city, data);
                    city = "";
                    data = new String[3];
                }
            }
        }
        return map;
    }
}
